name: demo

services:
  tele:
    image: mlan/asterisk
    platform: linux/amd64  # Добавляем явное указание платформы
    network_mode: bridge
    cap_add:
      - sys_ptrace
      - net_admin
      - net_raw
    ports:
      - "${SMS_PORT-8080}:${WEBSMSD_PORT:-80}"
      - "0.0.0.0:5060:5060/udp"
      - "0.0.0.0:5060:5060/tcp"
      - "0.0.0.0:5061:5061/tcp"
      - "0.0.0.0:10000-10099:10000-10099/udp"
    environment:
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-4}
      - HOSTNAME=${TELE_SRV-tele}.${DOMAIN-docker.localhost}
      # Убираем проблемные PulseAudio настройки
      # - PULSE_SERVER=unix:/run/pulse/socket
      # - PULSE_COOKIE=/run/pulse/cookie
      - WEBSMSD_PORT=${WEBSMSD_PORT-80}
    volumes:
      - tele-conf:/srv
      - ./config/extensions.conf:/etc/asterisk/extensions.conf:ro
      - ./config/cdr.conf:/etc/asterisk/cdr.conf:ro
      - ./config/cel.conf:/etc/asterisk/cel.conf:ro
      - ./config/acl.conf:/etc/asterisk/acl.conf:ro
      # Убираем проблемный volume с PulseAudio
      # - ./pulse:/run/pulse:rshared
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped  # Добавляем автоматический рестарт

volumes:
  tele-conf:
  